services:
  postgres-db:
    image: postgres:18
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: foodfast_db
    ports:
      - "5433:5432"  # host port 5433 â†’ container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodfast-net

  eureka-server:
    build: ./DoAnCNPM_Backend/eureka_server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres-db
    networks:
      - foodfast-net

  api-gateway:
    build: ./DoAnCNPM_Backend/api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - foodfast-net

  user-service:
    build: ./DoAnCNPM_Backend/user_service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  product-service:
    build: ./DoAnCNPM_Backend/product_service
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  order-service:
    build: ./DoAnCNPM_Backend/order_service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  payment-service:
    build: ./DoAnCNPM_Backend/payment_service
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net
  drone-service:
    build: ./DoAnCNPM_Backend/drone_service
    container_name: drone-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_APPLICATION_NAME=drone-service
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net
volumes:
  pgdata:

networks:
  foodfast-net:
    driver: bridge
  