services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: foodfast_db
    ports:
      - "5433:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodfast-net

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - foodfast-net

  eureka-server:
    build: ./DoAnCNPM_Backend/eureka_server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres-db
    networks:
      - foodfast-net

  api-gateway:
    build: ./DoAnCNPM_Backend/api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - foodfast-net

  user-service:
    build: ./DoAnCNPM_Backend/user_service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  product-service:
    build: ./DoAnCNPM_Backend/product_service
    container_name: product-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  order-service:
    build: ./DoAnCNPM_Backend/order_service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  payment-service:
    build: ./DoAnCNPM_Backend/payment_service
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  drone-service:
    build: ./DoAnCNPM_Backend/drone_service
    container_name: drone-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8089
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  restaurant-service:
    build: ./DoAnCNPM_Backend/restaurant-service
    container_name: restaurant-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/foodfast_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - eureka-server
    networks:
      - foodfast-net

  # ===== ThÃªm Node Exporter =====
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - foodfast-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - foodfast-net
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - drone-service
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1admin1
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - foodfast-net
    depends_on:
      - prometheus
  k6-exporter:
    image: node:18-alpine
    container_name: k6-exporter
    working_dir: /app
    volumes:
      - ./k6/scripts/k6-prometheus-server.js:/app/k6-prometheus-server.js
      - ./k6-results.json:/app/k6-results.json
    command: node k6-prometheus-server.js
    ports:
      - "6565:6565"
    networks:
      - foodfast-net
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6/tests:/scripts
      - ./k6/run-all-tests.sh:/run-all-tests.sh
    entrypoint: ["/bin/sh", "-c"]
    command: "sh /run-all-tests.sh"
    ports:
      - "9464:9464"
    networks:
      - foodfast-net
    depends_on:
      - prometheus



volumes:
  pgdata:
  mongodb_data:
  grafana-data:

networks:
  foodfast-net:
    driver: bridge
