services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: foodfast_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodfast-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./DoAnCNPM_Backend/eureka_server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - foodfast-net
    depends_on:
      postgres-db:
        condition: service_healthy

  api-gateway:
    build: ./DoAnCNPM_Backend/api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8085:8085"
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - foodfast-net

  user-service:
    build: ./DoAnCNPM_Backend/user_service
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/foodfast_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      postgres-db:
        condition: service_healthy
    networks:
      - foodfast-net

  product-service:
    build: ./DoAnCNPM_Backend/product_service
    container_name: product-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/foodfast_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      postgres-db:
        condition: service_healthy
    networks:
      - foodfast-net

  order-service:
    build: ./DoAnCNPM_Backend/order_service
    container_name: order-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: order-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/foodfast_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      postgres-db:
        condition: service_healthy
    networks:
      - foodfast-net

  payment-service:
    build: ./DoAnCNPM_Backend/payment_service
    container_name: payment-service
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_NAME: payment-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/foodfast_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      postgres-db:
        condition: service_healthy
    networks:
      - foodfast-net

volumes:
  pgdata:

networks:
  foodfast-net:
    driver: bridge
