global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Các service trong Docker network
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8081"]

  - job_name: "product-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["product-service:8080"]

  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["order-service:8082"]

  - job_name: "payment-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["payment-service:8084"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8085"]

  - job_name: "drone-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["drone-service:8086"]

  - job_name: "restaurant-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["restaurant-service:8083"]

  - job_name: "eureka-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["eureka-server:8761"]

  # ===== Thêm Node Exporter =====
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
